-- GED Prep database schema
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'student' check (role in ('student','admin')),
  last_seen timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, last_seen)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name',''),
    new.email,
    now()
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.chapters (
  id integer primary key,
  title text not null,
  description text,
  sort_order integer not null unique,
  created_at timestamptz not null default now()
);

insert into public.chapters (id,title,description,sort_order) values
(1,'Whole Numbers & Integers','Operations, signs, factors, multiples, and number properties.',1),
(2,'Fractions & Decimals','Equivalent forms and operations with fractions and decimals.',2),
(3,'Ratios, Rates & Proportions','Rates, proportions, scale, and unit reasoning.',3),
(4,'Percents & Applications','Percent change, discounts, tax, markup, and applications.',4),
(5,'Exponents & Roots','Powers, roots, scientific notation, and properties.',5),
(6,'Algebraic Expressions','Expressions, substitution, simplification, and factoring.',6),
(7,'Linear Equations & Inequalities','Solve and interpret equations and inequalities.',7),
(8,'Slope & Graphing','Slope, intercepts, lines, and coordinate relationships.',8),
(9,'Functions','Function notation, tables, rules, and interpretation.',9),
(10,'Geometry','Area, perimeter, volume, angles, and geometric reasoning.',10),
(11,'Statistics','Mean, median, range, spread, and data interpretation.',11),
(12,'Probability & Counting','Probability, combinations, permutations, and counting.',12),
(13,'Word Problems & Mixed Review','Multi-step GED-style applications and mixed review.',13)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  sort_order = excluded.sort_order;

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  chapter_id integer not null references public.chapters(id) on delete cascade,
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  correct_index integer not null check (correct_index >= 0),
  explanation text,
  difficulty text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  published boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint question_options_is_array check (jsonb_typeof(options) = 'array')
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  chapter_id integer not null references public.chapters(id) on delete cascade,
  score integer not null check (score >= 0),
  total integer not null check (total > 0),
  percentage numeric(5,2) generated always as ((score::numeric / total::numeric) * 100) stored,
  created_at timestamptz not null default now()
);

create index if not exists idx_questions_chapter_published on public.questions(chapter_id,published);
create index if not exists idx_attempts_user_created on public.quiz_attempts(user_id,created_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.chapters enable row level security;
alter table public.questions enable row level security;
alter table public.quiz_attempts enable row level security;

revoke all on table public.profiles, public.chapters, public.questions, public.quiz_attempts from anon;
grant select,insert,update on public.profiles to authenticated;
grant select on public.chapters to authenticated;
grant select on public.questions to authenticated;
grant select,insert on public.quiz_attempts to authenticated;

drop policy if exists profiles_self_select on public.profiles;
drop policy if exists profiles_self_update on public.profiles;
drop policy if exists profiles_admin_all on public.profiles;

create policy profiles_self_select on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

create policy profiles_self_update on public.profiles
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy profiles_admin_all on public.profiles
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists chapters_authenticated_read on public.chapters;
create policy chapters_authenticated_read on public.chapters
for select to authenticated using (true);

drop policy if exists questions_authenticated_read on public.questions;
create policy questions_authenticated_read on public.questions
for select to authenticated using (published = true or public.is_admin());

drop policy if exists questions_admin_write on public.questions;
create policy questions_admin_write on public.questions
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists attempts_self_select on public.quiz_attempts;
drop policy if exists attempts_self_insert on public.quiz_attempts;

create policy attempts_self_select on public.quiz_attempts
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy attempts_self_insert on public.quiz_attempts
for insert to authenticated
with check (user_id = auth.uid());

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists questions_set_updated_at on public.questions;
create trigger questions_set_updated_at
before update on public.questions
for each row execute procedure public.set_updated_at();

-- After creating your account, promote your own profile to admin in SQL:
-- update public.profiles set role='admin' where email='YOUR_EMAIL_HERE';
