-- Grade 12 Mathematics site tables.
-- Uses the existing Supabase Auth + public.profiles/admin role.

create table if not exists public.grade12_chapters (
  id integer primary key,
  title text not null,
  description text,
  sort_order integer not null unique,
  created_at timestamptz not null default now()
);

insert into public.grade12_chapters (id,title,description,sort_order) values
(1,'Complex Numbers','Complex numbers, algebraic form, modulus, argument, and applications.',1),
(2,'Matrix Algebra','Matrices, operations, determinants, inverses, and applications.',2),
(3,'Calculus Limits','Limits, continuity, and the foundations of calculus.',3),
(4,'Derivatives','Differentiation rules, gradients, and applications.',4),
(5,'Integration Vector','Integration techniques and vector applications.',5),
(6,'Differential Equations','First-order differential equations and mathematical models.',6),
(7,'Vector Spaces','Vectors, vector operations, and vector-space ideas.',7),
(8,'Linear Systems','Systems of linear equations and matrix methods.',8),
(9,'Probability Rules','Probability rules, conditional probability, and applications.',9),
(10,'Statistics Matrix','Statistics, data analysis, and matrix-based problems.',10),
(11,'Discrete Graphs','Discrete mathematics, graphs, and network ideas.',11),
(12,'Fourier Series','Fourier series, periodic functions, and basic expansions.',12)
on conflict (id) do update set
  title=excluded.title, description=excluded.description, sort_order=excluded.sort_order;

create table if not exists public.grade12_questions (
  id bigint generated by default as identity primary key,
  chapter_id integer not null references public.grade12_chapters(id) on delete cascade,
  prompt text not null,
  options jsonb not null default '[]'::jsonb,
  correct_index integer not null check (correct_index >= 0 and correct_index <= 3),
  explanation text,
  difficulty text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  published boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint grade12_options_array check (jsonb_typeof(options)='array')
);

create table if not exists public.grade12_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  chapter_id integer not null references public.grade12_chapters(id) on delete cascade,
  score integer not null check (score >= 0),
  total integer not null check (total > 0),
  percentage numeric(5,2) generated always as ((score::numeric / total::numeric)*100) stored,
  created_at timestamptz not null default now()
);

create index if not exists idx_grade12_questions_chapter_published
on public.grade12_questions(chapter_id,published);

create index if not exists idx_grade12_attempts_user_created
on public.grade12_attempts(user_id,created_at desc);

alter table public.grade12_chapters enable row level security;
alter table public.grade12_questions enable row level security;
alter table public.grade12_attempts enable row level security;

revoke all on table public.grade12_chapters, public.grade12_questions, public.grade12_attempts from anon;
grant select on public.grade12_chapters to authenticated;
grant select on public.grade12_questions to authenticated;
grant select,insert on public.grade12_attempts to authenticated;

drop policy if exists grade12_chapters_read on public.grade12_chapters;
create policy grade12_chapters_read on public.grade12_chapters
for select to authenticated using (true);

drop policy if exists grade12_questions_read on public.grade12_questions;
create policy grade12_questions_read on public.grade12_questions
for select to authenticated
using (published = true or public.is_admin());

drop policy if exists grade12_questions_admin_write on public.grade12_questions;
create policy grade12_questions_admin_write on public.grade12_questions
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists grade12_attempts_self_read on public.grade12_attempts;
create policy grade12_attempts_self_read on public.grade12_attempts
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists grade12_attempts_self_insert on public.grade12_attempts;
create policy grade12_attempts_self_insert on public.grade12_attempts
for insert to authenticated
with check (user_id = auth.uid());

create or replace function public.grade12_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at=now();
  return new;
end;
$$;

drop trigger if exists grade12_questions_set_updated_at on public.grade12_questions;
create trigger grade12_questions_set_updated_at
before update on public.grade12_questions
for each row execute procedure public.grade12_set_updated_at();

revoke execute on function public.grade12_set_updated_at() from public, anon, authenticated;
